# Generated by Django 3.0.6 on 2020-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200517_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='전화번호'),
        ),
    ]
