# Generated by Django 3.0.6 on 2020-05-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200517_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_processed',
            field=models.BooleanField(blank=True, default=False, verbose_name='처리상황'),
        ),
    ]
