
version: '3'
services:
  nginx:
    image: nginx:latest 
    ports:
      - "80:80"
    volumes:
      - .:/todo
      - ./config/nginx:/etc/nginx.conf.d 
    depends_on: 
      - web   
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    command: gunicorn config.wsgi:application == bind 0.0.0.0:8000
    volumes:
      - .:/todo
    expose: 
      - "8000"